---
- name: ssh
  hosts: all
  user: ubuntu
  gather_facts: no

  tasks:
    - name: wait for host
      wait_for_connection:
    - name: gather facts
      setup:
    - name: ssh copy id
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }} "
    - name: remove setup key
      ansible.posix.authorized_key:
        user: ubuntu
        state: absent
        key: "{{ lookup('file', '../key.pub') }} "
